# Cloudflare API keys

# Reccords to update
records:
 - zone_name: "bim42.com"
   record_name: "mediasm"
 - zone_name: "bim42.com"
   record_name: "jellyfin"
 - zone_name: "bim42.com"
   record_name: "komga"
 - zone_name: "bim42.com"
   record_name: "librechat"
 - zone_name: "bim42.com"
   record_name: "radarr"
 - zone_name: "bim42.com"
   record_name: "transmission"
 - zone_name: "bim42.com"
   record_name: "jellyseerr"
